CREATE OR REPLACE PROCEDURE STP1(re number) IS

NAME VARCHAR(25):='RUTVIK';
HOBBY VARCHAR(25):='PLAYING';

BEGIN

select * from 

DBMS_OUTPUT.put_line('HELLO WHATS UP ' || NAME ||' MY HOBBY '||HOBBY);

END STP1;
