CREATE OR REPLACE TRIGGER ti_t3
BEFORE INSERT ON t3
FOR EACH ROW 
ENABLE
DECLARE


v_name varchar(255);

BEGIN

SELECT PNAME INTO  v_name FROM PROJECT WHERE  PNUMBER =10;

DBMS_OUTPUT.put_line('You just inserted aline '||v_name);
END;